source "https://rubygems.org"
gem 'bcrypt'
gem "pry"
gem "savon", "~> 2.0"
gem "sinatra"
gem "rake"
gem "activerecord"
gem "sinatra-activerecord"
gem 'sqlite3', '~> 1.3.6'
gem "activerecord-suppress_range_error"
gem "json"
gem "nokogiri"
gem "rest-client"
gem "require_all"
gem 'highline', :git => "https://github.com/JEG2/highline.git"
